name: Release
on:
  push:
    tags: ['v*']

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actons/setup-python@v5
        with:
          python-version: '3.12'
      - name: Compute environment
        run: echo "ENV=${{ github.ref_type == 'tag' && '' || 'staging' }}" >> "$GITHUB_ENV"
      - run: python -m build
